/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.screens;


import com.conection.Conexion;
import com.curp.curp;
import static com.screens.LoginScreen.puntos_ant;
import static com.screens.LoginScreen.users;
import java.sql.ResultSetMetaData;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



public class MainScreen extends javax.swing.JFrame {

    Conexion cx;
    int xMouse,yMouse;
    
    public static int puntos_des;
    int points = 0;
  
    //int puntos_total = Puntos_ohm + Puntos_sp;
    
    LoginScreen lg = new LoginScreen();
    private String user = lg.users;
    private int puntos = lg.puntos_ant;
    

    
    
    public MainScreen() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        cx = new Conexion("sql10581290");
        
        
        try {
            
            DefaultTableModel model = new DefaultTableModel();
            leaderboard.setModel(model);
            
            PreparedStatement pst = null;
            ResultSet rs = null;
            
            String sql = "SELECT user,puntos FROM usuario ORDER BY puntos DESC ";
            
            
            pst = cx.conectar().prepareStatement(sql);
            rs = pst.executeQuery();
            
            
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnas = rsmd.getColumnCount();
            
            
            model.addColumn("Usuario");
            model.addColumn("Puntos");
            while(rs.next()){
                Object[] filas = new Object[columnas];
                for (int i = 0; i < columnas; i++){
                    filas[i] = rs.getObject(i+1);

                }
                model.addRow(filas);

            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
     

    }
        

    
    public void getPoints(int puntos){
        this.puntos = puntos;
        this.points = puntos;
    }
    curp c = new curp();

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/images/Icon.png"));
        return retValue;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Ranking_panel = new javax.swing.JPanel();
        Ranking_text = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        leaderboard = new javax.swing.JTable();
        Primer_puesto = new javax.swing.JLabel();
        Segundo_puesto = new javax.swing.JLabel();
        Tercer_puesto = new javax.swing.JLabel();
        Cuarto_puesto = new javax.swing.JLabel();
        Quinto_puesto = new javax.swing.JLabel();
        Sexto_puesto = new javax.swing.JLabel();
        Septimo_puesto = new javax.swing.JLabel();
        Ultimo_puesto = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitbtn = new javax.swing.JPanel();
        exit_btn = new javax.swing.JLabel();
        refreshbtn = new javax.swing.JPanel();
        refresh_btn = new javax.swing.JLabel();
        Ohm_Panel = new javax.swing.JPanel();
        Ohm_test = new javax.swing.JLabel();
        Ser_y_Par_panel = new javax.swing.JPanel();
        SyP_test = new javax.swing.JLabel();
        Kirchoff_panel = new javax.swing.JPanel();
        Kirchoff_test = new javax.swing.JLabel();
        Rl_Rc_panel = new javax.swing.JPanel();
        RL_test = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ranking_panel.setBackground(new java.awt.Color(7, 87, 91));
        Ranking_panel.setPreferredSize(new java.awt.Dimension(300, 500));

        Ranking_text.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Ranking_text.setForeground(new java.awt.Color(252, 217, 0));
        Ranking_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranking_text.setText("Ranking");

        jScrollPane2.setBackground(new java.awt.Color(7, 87, 91));
        jScrollPane2.setBorder(null);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setOpaque(false);

        leaderboard.setBackground(new java.awt.Color(7, 87, 91));
        leaderboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        leaderboard.setForeground(new java.awt.Color(252, 217, 0));
        leaderboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Usuario", "Puntos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        leaderboard.setAutoscrolls(false);
        leaderboard.setEnabled(false);
        leaderboard.setGridColor(new java.awt.Color(7, 87, 91));
        leaderboard.setOpaque(false);
        leaderboard.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(leaderboard);

        Primer_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Primer_puesto.setForeground(new java.awt.Color(252, 217, 0));
        Primer_puesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Primer_puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Primer.png"))); // NOI18N

        Segundo_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Segundo_puesto.setForeground(new java.awt.Color(252, 217, 0));
        Segundo_puesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Segundo_puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Segundo.png"))); // NOI18N

        Tercer_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Tercer_puesto.setForeground(new java.awt.Color(252, 217, 0));
        Tercer_puesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tercer_puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Tercero.png"))); // NOI18N

        Cuarto_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cuarto_puesto.setForeground(new java.awt.Color(252, 217, 0));
        Cuarto_puesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cuarto_puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Ajolote.png"))); // NOI18N

        Quinto_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Quinto_puesto.setForeground(new java.awt.Color(252, 217, 0));
        Quinto_puesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quinto_puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Camaleon.png"))); // NOI18N

        Sexto_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sexto_puesto.setForeground(new java.awt.Color(252, 217, 0));
        Sexto_puesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sexto_puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Koala.png"))); // NOI18N

        Septimo_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Septimo_puesto.setForeground(new java.awt.Color(252, 217, 0));
        Septimo_puesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Septimo_puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Morsa.png"))); // NOI18N

        Ultimo_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ultimo_puesto.setForeground(new java.awt.Color(252, 217, 0));
        Ultimo_puesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ultimo_puesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Tortuga.png"))); // NOI18N

        javax.swing.GroupLayout Ranking_panelLayout = new javax.swing.GroupLayout(Ranking_panel);
        Ranking_panel.setLayout(Ranking_panelLayout);
        Ranking_panelLayout.setHorizontalGroup(
            Ranking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ranking_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Ranking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ultimo_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ranking_text, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Ranking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Septimo_puesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(Sexto_puesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Quinto_puesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Segundo_puesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Primer_puesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tercer_puesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cuarto_puesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Ranking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ranking_panelLayout.createSequentialGroup()
                    .addContainerGap(52, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Ranking_panelLayout.setVerticalGroup(
            Ranking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ranking_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ranking_text, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Primer_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Segundo_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Tercer_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cuarto_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quinto_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sexto_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Septimo_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ultimo_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(Ranking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Ranking_panelLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        bg.add(Ranking_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 510));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(255, 255, 255));

        exit_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_btn.setText("X");
        exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        refreshbtn.setBackground(new java.awt.Color(255, 255, 255));

        refresh_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refresh_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refresh_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reset_btn.png"))); // NOI18N
        refresh_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refresh_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refresh_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout refreshbtnLayout = new javax.swing.GroupLayout(refreshbtn);
        refreshbtn.setLayout(refreshbtnLayout);
        refreshbtnLayout.setHorizontalGroup(
            refreshbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(refresh_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );
        refreshbtnLayout.setVerticalGroup(
            refreshbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(refresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 732, Short.MAX_VALUE)
                .addComponent(refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(refreshbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        Ohm_Panel.setBackground(new java.awt.Color(102, 165, 173));
        Ohm_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Ohm_test.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Ohm_test.setForeground(new java.awt.Color(252, 217, 0));
        Ohm_test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ohm_test.setText("Ley de ohm");
        Ohm_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ohm_testMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Ohm_PanelLayout = new javax.swing.GroupLayout(Ohm_Panel);
        Ohm_Panel.setLayout(Ohm_PanelLayout);
        Ohm_PanelLayout.setHorizontalGroup(
            Ohm_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(Ohm_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Ohm_PanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ohm_test, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Ohm_PanelLayout.setVerticalGroup(
            Ohm_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(Ohm_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Ohm_PanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ohm_test, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(Ohm_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 430, -1));

        Ser_y_Par_panel.setBackground(new java.awt.Color(102, 165, 173));
        Ser_y_Par_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SyP_test.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SyP_test.setForeground(new java.awt.Color(252, 217, 0));
        SyP_test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SyP_test.setText("Serie y Paralelo");
        SyP_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SyP_testMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Ser_y_Par_panelLayout = new javax.swing.GroupLayout(Ser_y_Par_panel);
        Ser_y_Par_panel.setLayout(Ser_y_Par_panelLayout);
        Ser_y_Par_panelLayout.setHorizontalGroup(
            Ser_y_Par_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SyP_test, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        Ser_y_Par_panelLayout.setVerticalGroup(
            Ser_y_Par_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SyP_test, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        bg.add(Ser_y_Par_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 430, 100));

        Kirchoff_panel.setBackground(new java.awt.Color(102, 165, 173));
        Kirchoff_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Kirchoff_test.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Kirchoff_test.setForeground(new java.awt.Color(252, 217, 0));
        Kirchoff_test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kirchoff_test.setText("Ley de Kirchoff");
        Kirchoff_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Kirchoff_testMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Kirchoff_panelLayout = new javax.swing.GroupLayout(Kirchoff_panel);
        Kirchoff_panel.setLayout(Kirchoff_panelLayout);
        Kirchoff_panelLayout.setHorizontalGroup(
            Kirchoff_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Kirchoff_test, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        Kirchoff_panelLayout.setVerticalGroup(
            Kirchoff_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Kirchoff_test, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        bg.add(Kirchoff_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 430, -1));

        Rl_Rc_panel.setBackground(new java.awt.Color(102, 165, 173));
        Rl_Rc_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RL_test.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RL_test.setForeground(new java.awt.Color(252, 217, 0));
        RL_test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RL_test.setText("Circuitos RL");
        RL_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RL_testMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Rl_Rc_panelLayout = new javax.swing.GroupLayout(Rl_Rc_panel);
        Rl_Rc_panel.setLayout(Rl_Rc_panelLayout);
        Rl_Rc_panelLayout.setHorizontalGroup(
            Rl_Rc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RL_test, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        Rl_Rc_panelLayout.setVerticalGroup(
            Rl_Rc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RL_test, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        bg.add(Rl_Rc_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 430, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 59, 70));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione un tema");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 26, 430, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_btnMouseClicked

    private void exit_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMouseEntered
        exitbtn.setBackground(Color.red);
    }//GEN-LAST:event_exit_btnMouseEntered

    private void exit_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMouseExited
        exitbtn.setBackground(Color.white);
    }//GEN-LAST:event_exit_btnMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void Ohm_testMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ohm_testMousePressed
        Ohm_Test ohm = new Ohm_Test();
        ohm.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_Ohm_testMousePressed

    private void refresh_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseClicked
        MainScreen ms = new MainScreen();
        System.out.println("buenas"+this.puntos);
        ms.setVisible(true);
        this.setVisible(false);
        
       
        
        
    }//GEN-LAST:event_refresh_btnMouseClicked

    private void refresh_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseEntered
        refreshbtn.setBackground(Color.blue);
    }//GEN-LAST:event_refresh_btnMouseEntered

    private void refresh_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseExited
        refreshbtn.setBackground(Color.white);
    }//GEN-LAST:event_refresh_btnMouseExited

    private void SyP_testMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SyP_testMousePressed
        S_P_Test sp = new S_P_Test();
        sp.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_SyP_testMousePressed

    private void Kirchoff_testMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kirchoff_testMousePressed
        Kirchoff_Test kf = new Kirchoff_Test();
        kf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Kirchoff_testMousePressed

    private void RL_testMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RL_testMousePressed
        RL_Test rl = new RL_Test();
        rl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RL_testMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cuarto_puesto;
    private javax.swing.JPanel Kirchoff_panel;
    private javax.swing.JLabel Kirchoff_test;
    private javax.swing.JPanel Ohm_Panel;
    private javax.swing.JLabel Ohm_test;
    private javax.swing.JLabel Primer_puesto;
    private javax.swing.JLabel Quinto_puesto;
    private javax.swing.JLabel RL_test;
    private javax.swing.JPanel Ranking_panel;
    private javax.swing.JLabel Ranking_text;
    private javax.swing.JPanel Rl_Rc_panel;
    private javax.swing.JLabel Segundo_puesto;
    private javax.swing.JLabel Septimo_puesto;
    private javax.swing.JPanel Ser_y_Par_panel;
    private javax.swing.JLabel Sexto_puesto;
    private javax.swing.JLabel SyP_test;
    private javax.swing.JLabel Tercer_puesto;
    private javax.swing.JLabel Ultimo_puesto;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel exit_btn;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable leaderboard;
    private javax.swing.JLabel refresh_btn;
    private javax.swing.JPanel refreshbtn;
    // End of variables declaration//GEN-END:variables
}
